name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Build on multiple systems: https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#configuring-a-build-matrix
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Boost 1.73.0
      shell: bash
      run: |
        curl -L https://boostorg.jfrog.io/artifactory/main/release/1.73.0/source/boost_1_73_0.zip --output boost_1_73_0.zip
        unzip -q boost_1_73_0.zip
    - name: Install Emscripten
      uses: mymindstorm/setup-emsdk@v10
      with:
        version: 2.0.27
        actions-cache-folder: 'emsdk-cache'
    - name: Install cmake
      uses: lukka/get-cmake@latest
    - name: Verify Emscripten
      shell: bash
      run: |
        em++ -v
    - name: CMake configure 
      run: emcmake cmake -S . -B build -DBoost_INCLUDE_DIR=boost_1_73_0/ -DBoost_LIBRARY_DIR=boost_1_73_0/
    - name: CMake build
      run: cmake --build build
    - name: CMake run tests
      cmake --build build --target test
